
source ~/.config/vim/options.vim
source ~/.config/vim/keybinds.vim
source ~/.config/vim/autocmd.vim
source ~/.config/vim/plugin.vim
source ~/.config/vim/color.vim
source ~/.config/vim/lsp.vim
source ~/.config/vim/lspconfig.vim






